"use client";

import { motion, useReducedMotion } from "motion/react";
import { FileText, Download } from "lucide-react";
import { SectionHeading, Button } from "@/components/ui";

export function LabReportSection() {
  const reduce = useReducedMotion();

  return (
    <section className="lab-report-section">
      <div className="container">
        <SectionHeading
          eyebrow="Documentation"
          title="Generate your lab report."
          description="Automatically compile your experiment results, graphs, equations, and analysis into a professional PDF."
        />

        <div className="report-layout">
          <motion.div
            className="report-preview"
            initial={reduce ? false : { opacity: 0, x: -32 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true, amount: 0.35 }}
            transition={{ duration: 0.65 }}
          >
            <div className="report-mockup">
              <div className="report-header">
                <FileText size={24} />
                <div>
                  <h4>Projectile Motion Lab</h4>
                  <span>Experiment Report</span>
                </div>
              </div>

              <div className="report-content">
                <motion.div
                  className="report-section"
                  initial={{ opacity: 0, y: 10 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: 0.3 }}
                >
                  <span className="section-number">I.</span>
                  <div>
                    <h5>Objective</h5>
                    <p>Analyze projectile motion by tracking a thrown ball and comparing theoretical vs actual trajectory.</p>
                  </div>
                </motion.div>

                <motion.div
                  className="report-section"
                  initial={{ opacity: 0, y: 10 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: 0.4 }}
                >
                  <span className="section-number">II.</span>
                  <div>
                    <h5>Measurements</h5>
                    <ul>
                      <li>Launch Angle: 38°</li>
                      <li>Initial Velocity: 5.8 m/s</li>
                      <li>Maximum Height: 0.82 m</li>
                      <li>Range: 5.1 m</li>
                      <li>Flight Time: 0.62 s</li>
                    </ul>
                  </div>
                </motion.div>

                <motion.div
                  className="report-section"
                  initial={{ opacity: 0, y: 10 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: 0.5 }}
                >
                  <span className="section-number">III.</span>
                  <div>
                    <h5>Analysis</h5>
                    <p>Theory predicts 5.4 m range; actual was 5.1 m (5.5% error). Difference due to air resistance.</p>
                  </div>
                </motion.div>

                <motion.div
                  className="report-section"
                  initial={{ opacity: 0, y: 10 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: 0.6 }}
                >
                  <span className="section-number">IV.</span>
                  <div>
                    <h5>Conclusion</h5>
                    <p>Physics Score: 87/100. Predictions matched reality closely. Air resistance was primary error factor.</p>
                  </div>
                </motion.div>
              </div>

              <div className="report-footer">
                <span>Generated by Kinetix</span>
                <span>2026-08-27</span>
              </div>
            </div>
          </motion.div>

          <motion.div
            className="report-features"
            initial={reduce ? false : { opacity: 0, x: 32 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true, amount: 0.35 }}
            transition={{ duration: 0.65, delay: 0.1 }}
          >
            <div className="feature-list">
              {[
                {
                  title: "Experiment Summary",
                  description: "Date, time, object, and environmental conditions recorded automatically.",
                },
                {
                  title: "Physics Metrics",
                  description: "All measurements: angle, velocity, height, range, and flight time included.",
                },
                {
                  title: "Graph Visualizations",
                  description: "Trajectory, velocity vs time, and position vs time graphs embedded.",
                },
                {
                  title: "Equations",
                  description: "Mathematical formulas used, with actual values filled in from your throw.",
                },
                {
                  title: "Theory vs Reality",
                  description: "Side-by-side comparison with error analysis and explanation.",
                },
                {
                  title: "Score Breakdown",
                  description: "Your Physics Score with accuracy percentages for each prediction.",
                },
              ].map((feature, index) => (
                <motion.div
                  key={feature.title}
                  className="feature-item"
                  initial={reduce ? false : { opacity: 0, y: 14 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true, amount: 0.5 }}
                  transition={{ delay: 0.2 + index * 0.08 }}
                >
                  <div className="feature-check">✓</div>
                  <div>
                    <h4>{feature.title}</h4>
                    <p>{feature.description}</p>
                  </div>
                </motion.div>
              ))}
            </div>

            <motion.div
              className="report-cta"
              initial={reduce ? false : { opacity: 0, y: 16 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, amount: 0.5 }}
              transition={{ delay: 0.65 }}
            >
              <Button href="/app/dashboard">
                Generate Your Report
              </Button>
            </motion.div>
          </motion.div>
        </div>
      </div>
    </section>
  );
}
