"use client";

import { useRef, useEffect, useState } from "react";
import { motion, useReducedMotion, useInView } from "motion/react";
import { FileText, Download } from "lucide-react";
import { SectionHeading, Button } from "@/components/ui";

export function LabReportSection() {
  const reduce = useReducedMotion();
  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);

  const contentRef = useRef<HTMLDivElement>(null);
  const featuresRef = useRef<HTMLDivElement>(null);
  
  const isContentInView = useInView(contentRef, { once: true, amount: 0.2 });
  const isFeaturesInView = useInView(featuresRef, { once: true, amount: 0.2 });

  const listVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1,
      },
    },
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 10 },
    visible: { opacity: 1, y: 0, transition: { duration: 0.5 } },
  };

  const contentState = mounted ? (reduce ? "visible" : (isContentInView ? "visible" : "hidden")) : "visible";
  const featuresState = mounted ? (reduce ? "visible" : (isFeaturesInView ? "visible" : "hidden")) : "visible";

  return (
    <section className="lab-report-section">
      <div className="container">
        <SectionHeading
          eyebrow="Documentation"
          title="Generate your lab report."
          description="Automatically compile your experiment results, graphs, equations, and analysis into a professional PDF."
        />

        <div className="report-layout">
          <motion.div
            className="report-preview"
            initial={reduce ? false : { opacity: 0, x: -32 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true, amount: 0.35 }}
            transition={{ duration: 0.65 }}
          >
            <div className="report-mockup">
              <div className="report-header">
                <FileText size={24} />
                <div>
                  <h4>Projectile Motion Lab</h4>
                  <span>Experiment Report</span>
                </div>
              </div>

              <motion.div 
                ref={contentRef}
                className="report-content"
                variants={listVariants}
                initial="visible"
                animate={contentState}
              >
                <motion.div className="report-section" variants={itemVariants}>
                  <span className="section-number">I.</span>
                  <div>
                    <h5>Objective</h5>
                    <p>Analyze projectile motion by tracking a thrown ball and comparing theoretical vs actual trajectory.</p>
                  </div>
                </motion.div>

                <motion.div className="report-section" variants={itemVariants}>
                  <span className="section-number">II.</span>
                  <div>
                    <h5>Measurements</h5>
                    <ul>
                      <li>Launch Angle: 38°</li>
                      <li>Initial Velocity: 5.8 m/s</li>
                      <li>Maximum Height: 0.82 m</li>
                      <li>Range: 5.1 m</li>
                      <li>Flight Time: 0.62 s</li>
                    </ul>
                  </div>
                </motion.div>

                <motion.div className="report-section" variants={itemVariants}>
                  <span className="section-number">III.</span>
                  <div>
                    <h5>Analysis</h5>
                    <p>Theory predicts 5.4 m range; actual was 5.1 m (5.5% error). Difference due to air resistance.</p>
                  </div>
                </motion.div>

                <motion.div className="report-section" variants={itemVariants}>
                  <span className="section-number">IV.</span>
                  <div>
                    <h5>Conclusion</h5>
                    <p>Physics Score: 87/100. Predictions matched reality closely. Air resistance was primary error factor.</p>
                  </div>
                </motion.div>
              </motion.div>

              <div className="report-footer">
                <span>Generated by Kinetix</span>
                <span>2026-08-27</span>
              </div>
            </div>
          </motion.div>

          <motion.div
            className="report-features"
            initial={reduce ? false : { opacity: 0, x: 32 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true, amount: 0.35 }}
            transition={{ duration: 0.65, delay: 0.1 }}
          >
            <motion.div 
              ref={featuresRef}
              className="feature-list"
              variants={listVariants}
              initial="visible"
              animate={featuresState}
            >
              {[
                {
                  title: "Experiment Summary",
                  description: "Date, time, object, and environmental conditions recorded automatically.",
                },
                {
                  title: "Physics Metrics",
                  description: "All measurements: angle, velocity, height, range, and flight time included.",
                },
                {
                  title: "Graph Visualizations",
                  description: "Trajectory, velocity vs time, and position vs time graphs embedded.",
                },
                {
                  title: "Equations",
                  description: "Mathematical formulas used, with actual values filled in from your throw.",
                },
                {
                  title: "Theory vs Reality",
                  description: "Side-by-side comparison with error analysis and explanation.",
                },
                {
                  title: "Score Breakdown",
                  description: "Your Physics Score with accuracy percentages for each prediction.",
                },
              ].map((feature) => (
                <motion.div
                  key={feature.title}
                  className="feature-item"
                  variants={itemVariants}
                >
                  <div className="feature-check">✓</div>
                  <div>
                    <h4>{feature.title}</h4>
                    <p>{feature.description}</p>
                  </div>
                </motion.div>
              ))}
            </motion.div>

            <motion.div
              className="report-cta"
              initial={reduce ? false : { opacity: 0, y: 16 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, amount: 0.5 }}
              transition={{ delay: 0.65 }}
            >
              <Button href="/app/dashboard">
                Generate Your Report
              </Button>
            </motion.div>
          </motion.div>
        </div>
      </div>
    </section>
  );
}
